### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by askchike** [olivierbellone/stripe-java-examples#1]
Hi Olivier,
Can you please assist?

I literally just downloaded this sample project then compiled and executed as per the instructions.  This is the error output I got:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.023 s
[INFO] Finished at: 2016-02-17T12:58:14-05:00
[INFO] Final Memory: 8M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project stripe-oauth-spark2: An exception occured while executing the Java class. null: InvocationTargetException: /Users/CMac/Documents/Ask%20Chike/Stripe%20Connect/stripe-java-examples-master/stripe-oauth-spark2/target/classes/stripe/keys.ini (No such file or directory) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by olivierbellone** [comment]
Hey @askchike, sorry for the very very late reply! (It turns out I wasn't subscribed to my own repository's notifications...)

I imagine that you've either fixed the problem or moved on since last February, but just in case: according to the error message, the `keys.ini` file is missing. Can you check that the file at `stripe-oauth-spark2/src/main/resources/stripe/keys.ini` exists and contains your client_id and API key, then re-run `mvn clean && mvn compile`?
